version: '3.5'

services:

  etcd:
    image: quay.io/coreos/etcd:v3.2.25
    ports:
      - 2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379

  example:
    image: abilioesteves/prom-expressjs
    ports:
      - 23498
    environment:
      - REGISTRY_ETCD_URL=http://etcd:2379

  bb-promster-l1:
    build: .
    image: labbsr0x/bb-promster:latest
    ports:
      - 9090
    environment:
      - BB_PROMSTER_LEVEL=1
      - ETCD_URLS=http://etcd:2379
      - SCRAPE_ETCD_PATH=/services/example
      # - TLS_INSECURE=true
      # - SCRAPE_PATHS=/your-custom-metrics-path
      # - SCHEME="https"

  bb-promster-l2:
    image: labbsr0x/bb-promster:latest
    depends_on:
      - bb-promster-l1
    ports:
      - 9090
    environment:
      - BB_PROMSTER_LEVEL=2
      - ETCD_URLS=http://etcd:2379
    
  bb-promster-l3:
    image: labbsr0x/bb-promster:latest
    depends_on:
      - bb-promster-l2
    ports:
      - 9090
    environment:
      - BB_PROMSTER_LEVEL=3
      - ETCD_URLS=http://etcd:2379
